[general]

host = "::"
port = 8080
root = "/site"

cache-control-headers = true
compression = true
security-headers = true

log-level = "warn"
page404 = "/site/404.html"

directory-listing = false
log-remote-address = false
redirect-trailing-slash = true

[advanced]

[[advanced.redirects]]
source = "{**}/index.html"
destination = "$1/"
kind = 301

[[advanced.redirects]]
source = "{**}/{*}.html"
destination = "$1/$2/"
kind = 301

[[advanced.redirects]]
source = "/res/images/sense/{*.*}"
destination = "/sense-api/$1"
kind = 301

[[advanced.redirects]]
source = "/res/images/wemo/{*.*}"
destination = "/monitoring-power-with-wemo/$1"
kind = 301

[[advanced.redirects]]
source = "/res/images/docker/{*.*}"
destination = "/docker-automatic-nginx-proxy/$1"
kind = 301

[[advanced.redirects]]
source = "/res/images/https/{*.*}"
destination = "/why-you-should-be-using-https/$1"
kind = 301

[[advanced.redirects]]
source = "/res/images/yubikey/{*.*}"
destination = "/offline-gnupg-master-yubikey-subkeys/$1"
kind = 301

[[advanced.redirects]]
source = "/res/images/ssh/{*.*}"
destination = "/shoring-up-sshd/$1"
kind = 301

[[advanced.redirects]]
source = "/res/images/android-tests/{*.*}"
destination = "/android-tests-espresso-spoon/$1"
kind = 301

[[advanced.redirects]]
source = "/res/images/dns/{*.*}"
destination = "/top-sites-dns-providers/$1"
kind = 301

[[advanced.redirects]]
source = "/res/images/erl/{*.*}"
destination = "/dns-over-tls-on-edgerouter-lite/$1"
kind = 301

[[advanced.redirects]]
source = "/res/images/aoc/{*.*}"
destination = "/over-the-top-optimisations-in-nim/$1"
kind = 301

[[advanced.redirects]]
source = "/res/images/nim/{*.*}"
destination = "/over-the-top-optimisations-in-nim/$1"
kind = 301

[[advanced.redirects]]
source = "/res/images/debugging/{*.*}"
destination = "/debugging-beyond-the-debugger/$1"
kind = 301

[[advanced.redirects]]
source = "/res/images/unsplash/{*.*}"
destination = "/debugging-beyond-the-debugger/$1"
kind = 301

[[advanced.redirects]]
source = "/res/images/obfuscation/{*.*}"
destination = "/obfuscating-kotlin-proguard/$1"
kind = 301

[[advanced.redirects]]
source = "/20??/??/??/{*}/"
destination = "/$1/"
kind = 301

[[advanced.redirects]]
source = "/page/{*}/"
destination = "/posts/$1/"
kind = 301

[[advanced.redirects]]
source = "/poem/{*}/"
destination = "/$1/"
kind = 301

[[advanced.redirects]]
source = "/misc/snippets/"
destination = "/snippets/"
kind = 301