// Code generated by cmd/generate. DO NOT EDIT.
//go:generate go run ../../cmd/generate

package main

import (
	admin "chameth.com/chameth.com/admin"
	assets "chameth.com/chameth.com/assets"
	features "chameth.com/chameth.com/features"
	featuresBoardgamesList "chameth.com/chameth.com/features/boardgames/list"
	featuresBoardgamesPlayed "chameth.com/chameth.com/features/boardgames/played"
	featuresContact "chameth.com/chameth.com/features/contact"
	featuresContactForm "chameth.com/chameth.com/features/contact/form"
	featuresFeeds "chameth.com/chameth.com/features/feeds"
	featuresFilms "chameth.com/chameth.com/features/films"
	featuresFilmsList "chameth.com/chameth.com/features/films/list"
	featuresFilmsRatingdistribution "chameth.com/chameth.com/features/films/ratingdistribution"
	featuresFilmsRecent "chameth.com/chameth.com/features/films/recent"
	featuresFilmsReview "chameth.com/chameth.com/features/films/review"
	featuresFilmsReviews "chameth.com/chameth.com/features/films/reviews"
	featuresFilmsSearch "chameth.com/chameth.com/features/films/search"
	featuresFilmsWatched "chameth.com/chameth.com/features/films/watched"
	featuresMediaAudio "chameth.com/chameth.com/features/media/audio"
	featuresMediaFigure "chameth.com/chameth.com/features/media/figure"
	featuresMediaVideo "chameth.com/chameth.com/features/media/video"
	featuresMetrics "chameth.com/chameth.com/features/metrics"
	featuresMusic "chameth.com/chameth.com/features/music"
	featuresMusicNowplaying "chameth.com/chameth.com/features/music/nowplaying"
	featuresMusicTopalbums "chameth.com/chameth.com/features/music/topalbums"
	featuresMusicTopartists "chameth.com/chameth.com/features/music/topartists"
	featuresNod "chameth.com/chameth.com/features/nod"
	featuresNodForm "chameth.com/chameth.com/features/nod/form"
	featuresPosts "chameth.com/chameth.com/features/posts"
	featuresPostsLink "chameth.com/chameth.com/features/posts/link"
	featuresPostsRecent "chameth.com/chameth.com/features/posts/recent"
	featuresPrints "chameth.com/chameth.com/features/prints"
	featuresProjects "chameth.com/chameth.com/features/projects"
	featuresShortcodesLink "chameth.com/chameth.com/features/shortcodes/link"
	featuresShortcodesRating "chameth.com/chameth.com/features/shortcodes/rating"
	featuresShortcodesSidenote "chameth.com/chameth.com/features/shortcodes/sidenote"
	featuresShortcodesUpdate "chameth.com/chameth.com/features/shortcodes/update"
	featuresShortcodesWarning "chameth.com/chameth.com/features/shortcodes/warning"
	featuresSitemap "chameth.com/chameth.com/features/sitemap"
	featuresSnippets "chameth.com/chameth.com/features/snippets"
	featuresSudo "chameth.com/chameth.com/features/sudo"
	featuresSyndications "chameth.com/chameth.com/features/syndications"
	featuresSyndicationsDisplay "chameth.com/chameth.com/features/syndications/display"
	featuresWalksDistance "chameth.com/chameth.com/features/walks/distance"
	featuresWalksList "chameth.com/chameth.com/features/walks/list"
	featuresWalksSpeed "chameth.com/chameth.com/features/walks/speed"
	featuresWow "chameth.com/chameth.com/features/wow"
	featuresWowChar "chameth.com/chameth.com/features/wow/char"
	handlers "chameth.com/chameth.com/handlers"
)

func (s *site) registerAssets() {
	assets.RegisterAssets(s.Assets)
	features.RegisterAssets(s.Assets)
	featuresFeeds.RegisterAssets(s.Assets)
	featuresShortcodesRating.RegisterAssets(s.Assets)
}

func (s *site) registerShortcodes() {
	featuresBoardgamesList.RegisterShortcodes(s.Shortcodes)
	featuresBoardgamesPlayed.RegisterShortcodes(s.Shortcodes)
	featuresContactForm.RegisterShortcodes(s.Shortcodes)
	featuresFilmsList.RegisterShortcodes(s.Shortcodes)
	featuresFilmsRatingdistribution.RegisterShortcodes(s.Shortcodes)
	featuresFilmsRecent.RegisterShortcodes(s.Shortcodes)
	featuresFilmsReview.RegisterShortcodes(s.Shortcodes)
	featuresFilmsReviews.RegisterShortcodes(s.Shortcodes)
	featuresFilmsSearch.RegisterShortcodes(s.Shortcodes)
	featuresFilmsWatched.RegisterShortcodes(s.Shortcodes)
	featuresMediaAudio.RegisterShortcodes(s.Shortcodes)
	featuresMediaFigure.RegisterShortcodes(s.Shortcodes)
	featuresMediaVideo.RegisterShortcodes(s.Shortcodes)
	featuresMusicNowplaying.RegisterShortcodes(s.Shortcodes)
	featuresMusicTopalbums.RegisterShortcodes(s.Shortcodes)
	featuresMusicTopartists.RegisterShortcodes(s.Shortcodes)
	featuresNodForm.RegisterShortcodes(s.Shortcodes)
	featuresPostsLink.RegisterShortcodes(s.Shortcodes)
	featuresPostsRecent.RegisterShortcodes(s.Shortcodes)
	featuresShortcodesLink.RegisterShortcodes(s.Shortcodes)
	featuresShortcodesRating.RegisterShortcodes(s.Shortcodes)
	featuresShortcodesSidenote.RegisterShortcodes(s.Shortcodes)
	featuresShortcodesUpdate.RegisterShortcodes(s.Shortcodes)
	featuresShortcodesWarning.RegisterShortcodes(s.Shortcodes)
	featuresSyndicationsDisplay.RegisterShortcodes(s.Shortcodes)
	featuresWalksDistance.RegisterShortcodes(s.Shortcodes)
	featuresWalksList.RegisterShortcodes(s.Shortcodes)
	featuresWalksSpeed.RegisterShortcodes(s.Shortcodes)
	featuresWowChar.RegisterShortcodes(s.Shortcodes)
}

func (s *site) registerRoutes() {
	featuresContact.RegisterRoutes(s.Mux)
	featuresFeeds.RegisterRoutes(s.Mux)
	featuresFilms.RegisterRoutes(s.Mux)
	featuresNod.RegisterRoutes(s.Mux)
	featuresPosts.RegisterRoutes(s.Mux)
	featuresPrints.RegisterRoutes(s.Mux)
	featuresProjects.RegisterRoutes(s.Mux)
	featuresSitemap.RegisterRoutes(s.Mux)
	featuresSnippets.RegisterRoutes(s.Mux)
	featuresSudo.RegisterRoutes(s.Mux)
	handlers.RegisterRoutes(s.Mux, s.Assets)
}

func (s *site) launchGoroutines() {
	go admin.RegisterGoroutine(s.Tailscale, s.Assets)()
	go featuresMetrics.RegisterGoroutine()()
	go featuresMusic.RegisterGoroutine(s.Context, s.Tailscale)()
	go featuresPosts.RegisterGoroutine(s.Context)()
	go featuresSyndications.RegisterGoroutine(s.Context)()
	go featuresWow.RegisterGoroutine(s.Context)()
}
