// Code generated by cmd/generate. DO NOT EDIT.
//go:generate go run ../../cmd/generate

package main

import (
	assets "chameth.com/chameth.com/assets"
	features "chameth.com/chameth.com/features"
	featuresBoardgamesList "chameth.com/chameth.com/features/boardgames/list"
	featuresBoardgamesPlayed "chameth.com/chameth.com/features/boardgames/played"
	featuresContact "chameth.com/chameth.com/features/contact"
	featuresContactForm "chameth.com/chameth.com/features/contact/form"
	featuresFeeds "chameth.com/chameth.com/features/feeds"
	featuresFilms "chameth.com/chameth.com/features/films"
	featuresFilmsList "chameth.com/chameth.com/features/films/list"
	featuresFilmsRatingdistribution "chameth.com/chameth.com/features/films/ratingdistribution"
	featuresFilmsRecent "chameth.com/chameth.com/features/films/recent"
	featuresFilmsReview "chameth.com/chameth.com/features/films/review"
	featuresFilmsReviews "chameth.com/chameth.com/features/films/reviews"
	featuresFilmsSearch "chameth.com/chameth.com/features/films/search"
	featuresFilmsWatched "chameth.com/chameth.com/features/films/watched"
	featuresMediaAudio "chameth.com/chameth.com/features/media/audio"
	featuresMediaFigure "chameth.com/chameth.com/features/media/figure"
	featuresMediaVideo "chameth.com/chameth.com/features/media/video"
	featuresMusicNowplaying "chameth.com/chameth.com/features/music/nowplaying"
	featuresMusicTopalbums "chameth.com/chameth.com/features/music/topalbums"
	featuresMusicTopartists "chameth.com/chameth.com/features/music/topartists"
	featuresNod "chameth.com/chameth.com/features/nod"
	featuresNodForm "chameth.com/chameth.com/features/nod/form"
	featuresPosts "chameth.com/chameth.com/features/posts"
	featuresPostsLink "chameth.com/chameth.com/features/posts/link"
	featuresPostsRecent "chameth.com/chameth.com/features/posts/recent"
	featuresPrints "chameth.com/chameth.com/features/prints"
	featuresProjects "chameth.com/chameth.com/features/projects"
	featuresShortcodes "chameth.com/chameth.com/features/shortcodes"
	featuresShortcodesLink "chameth.com/chameth.com/features/shortcodes/link"
	featuresShortcodesRating "chameth.com/chameth.com/features/shortcodes/rating"
	featuresShortcodesSidenote "chameth.com/chameth.com/features/shortcodes/sidenote"
	featuresShortcodesUpdate "chameth.com/chameth.com/features/shortcodes/update"
	featuresShortcodesWarning "chameth.com/chameth.com/features/shortcodes/warning"
	featuresSitemap "chameth.com/chameth.com/features/sitemap"
	featuresSnippets "chameth.com/chameth.com/features/snippets"
	featuresSudo "chameth.com/chameth.com/features/sudo"
	featuresSyndicationsDisplay "chameth.com/chameth.com/features/syndications/display"
	featuresWalksDistance "chameth.com/chameth.com/features/walks/distance"
	featuresWalksList "chameth.com/chameth.com/features/walks/list"
	featuresWalksSpeed "chameth.com/chameth.com/features/walks/speed"
	featuresWowChar "chameth.com/chameth.com/features/wow/char"
	handlers "chameth.com/chameth.com/handlers"
	http "net/http"
)

func registerAssets(mgr *assets.Manager) {
	assets.RegisterAssets(mgr)
	features.RegisterAssets(mgr)
	featuresFeeds.RegisterAssets(mgr)
	featuresShortcodesRating.RegisterAssets(mgr)
}

func registerShortcodes(mgr *featuresShortcodes.Manager) {
	featuresBoardgamesList.RegisterShortcodes(mgr)
	featuresBoardgamesPlayed.RegisterShortcodes(mgr)
	featuresContactForm.RegisterShortcodes(mgr)
	featuresFilmsList.RegisterShortcodes(mgr)
	featuresFilmsRatingdistribution.RegisterShortcodes(mgr)
	featuresFilmsRecent.RegisterShortcodes(mgr)
	featuresFilmsReview.RegisterShortcodes(mgr)
	featuresFilmsReviews.RegisterShortcodes(mgr)
	featuresFilmsSearch.RegisterShortcodes(mgr)
	featuresFilmsWatched.RegisterShortcodes(mgr)
	featuresMediaAudio.RegisterShortcodes(mgr)
	featuresMediaFigure.RegisterShortcodes(mgr)
	featuresMediaVideo.RegisterShortcodes(mgr)
	featuresMusicNowplaying.RegisterShortcodes(mgr)
	featuresMusicTopalbums.RegisterShortcodes(mgr)
	featuresMusicTopartists.RegisterShortcodes(mgr)
	featuresNodForm.RegisterShortcodes(mgr)
	featuresPostsLink.RegisterShortcodes(mgr)
	featuresPostsRecent.RegisterShortcodes(mgr)
	featuresShortcodesLink.RegisterShortcodes(mgr)
	featuresShortcodesRating.RegisterShortcodes(mgr)
	featuresShortcodesSidenote.RegisterShortcodes(mgr)
	featuresShortcodesUpdate.RegisterShortcodes(mgr)
	featuresShortcodesWarning.RegisterShortcodes(mgr)
	featuresSyndicationsDisplay.RegisterShortcodes(mgr)
	featuresWalksDistance.RegisterShortcodes(mgr)
	featuresWalksList.RegisterShortcodes(mgr)
	featuresWalksSpeed.RegisterShortcodes(mgr)
	featuresWowChar.RegisterShortcodes(mgr)
}

func registerRoutes(mux *http.ServeMux, assetsManager *assets.Manager) {
	featuresContact.RegisterRoutes(mux)
	featuresFeeds.RegisterRoutes(mux)
	featuresFilms.RegisterRoutes(mux)
	featuresNod.RegisterRoutes(mux)
	featuresPosts.RegisterRoutes(mux)
	featuresPrints.RegisterRoutes(mux)
	featuresProjects.RegisterRoutes(mux)
	featuresSitemap.RegisterRoutes(mux)
	featuresSnippets.RegisterRoutes(mux)
	featuresSudo.RegisterRoutes(mux)
	handlers.RegisterRoutes(mux, assetsManager)
}
