// Code generated by cmd/generate. DO NOT EDIT.
//go:generate go run ../../cmd/generate

package main

import (
	assets "chameth.com/chameth.com/assets"
	features "chameth.com/chameth.com/features"
	featuresAdmin "chameth.com/chameth.com/features/admin"
	featuresBoardgamesAdmin "chameth.com/chameth.com/features/boardgames/admin"
	featuresBoardgamesList "chameth.com/chameth.com/features/boardgames/list"
	featuresBoardgamesPlayed "chameth.com/chameth.com/features/boardgames/played"
	featuresContact "chameth.com/chameth.com/features/contact"
	featuresContactForm "chameth.com/chameth.com/features/contact/form"
	featuresFeeds "chameth.com/chameth.com/features/feeds"
	featuresFilms "chameth.com/chameth.com/features/films"
	featuresFilmsAdmin "chameth.com/chameth.com/features/films/admin"
	featuresFilmsList "chameth.com/chameth.com/features/films/list"
	featuresFilmsRatingdistribution "chameth.com/chameth.com/features/films/ratingdistribution"
	featuresFilmsRecent "chameth.com/chameth.com/features/films/recent"
	featuresFilmsReview "chameth.com/chameth.com/features/films/review"
	featuresFilmsReviews "chameth.com/chameth.com/features/films/reviews"
	featuresFilmsSearch "chameth.com/chameth.com/features/films/search"
	featuresFilmsWatched "chameth.com/chameth.com/features/films/watched"
	featuresGoimports "chameth.com/chameth.com/features/goimports"
	featuresGoimportsAdmin "chameth.com/chameth.com/features/goimports/admin"
	featuresMedia "chameth.com/chameth.com/features/media"
	featuresMediaAdmin "chameth.com/chameth.com/features/media/admin"
	featuresMediaAudio "chameth.com/chameth.com/features/media/audio"
	featuresMediaFigure "chameth.com/chameth.com/features/media/figure"
	featuresMediaLabelledfigure "chameth.com/chameth.com/features/media/labelledfigure"
	featuresMediaVideo "chameth.com/chameth.com/features/media/video"
	featuresMetrics "chameth.com/chameth.com/features/metrics"
	featuresMusic "chameth.com/chameth.com/features/music"
	featuresMusicNowplaying "chameth.com/chameth.com/features/music/nowplaying"
	featuresMusicTopalbums "chameth.com/chameth.com/features/music/topalbums"
	featuresMusicTopartists "chameth.com/chameth.com/features/music/topartists"
	featuresNod "chameth.com/chameth.com/features/nod"
	featuresNodForm "chameth.com/chameth.com/features/nod/form"
	featuresPages "chameth.com/chameth.com/features/pages"
	featuresPagesAdmin "chameth.com/chameth.com/features/pages/admin"
	featuresPastes "chameth.com/chameth.com/features/pastes"
	featuresPastesAdmin "chameth.com/chameth.com/features/pastes/admin"
	featuresPoems "chameth.com/chameth.com/features/poems"
	featuresPoemsAdmin "chameth.com/chameth.com/features/poems/admin"
	featuresPosts "chameth.com/chameth.com/features/posts"
	featuresPostsAdmin "chameth.com/chameth.com/features/posts/admin"
	featuresPostsLink "chameth.com/chameth.com/features/posts/link"
	featuresPostsRecent "chameth.com/chameth.com/features/posts/recent"
	featuresPrints "chameth.com/chameth.com/features/prints"
	featuresProjects "chameth.com/chameth.com/features/projects"
	featuresProjectsAdmin "chameth.com/chameth.com/features/projects/admin"
	featuresRouting "chameth.com/chameth.com/features/routing"
	featuresShortcodesLink "chameth.com/chameth.com/features/shortcodes/link"
	featuresShortcodesRating "chameth.com/chameth.com/features/shortcodes/rating"
	featuresShortcodesSidenote "chameth.com/chameth.com/features/shortcodes/sidenote"
	featuresShortcodesUpdate "chameth.com/chameth.com/features/shortcodes/update"
	featuresShortcodesWarning "chameth.com/chameth.com/features/shortcodes/warning"
	featuresSitemap "chameth.com/chameth.com/features/sitemap"
	featuresSnippets "chameth.com/chameth.com/features/snippets"
	featuresSnippetsAdmin "chameth.com/chameth.com/features/snippets/admin"
	featuresSudo "chameth.com/chameth.com/features/sudo"
	featuresSyndications "chameth.com/chameth.com/features/syndications"
	featuresSyndicationsAdmin "chameth.com/chameth.com/features/syndications/admin"
	featuresSyndicationsDisplay "chameth.com/chameth.com/features/syndications/display"
	featuresVideogamesAdmin "chameth.com/chameth.com/features/videogames/admin"
	featuresWalksAdmin "chameth.com/chameth.com/features/walks/admin"
	featuresWalksDistance "chameth.com/chameth.com/features/walks/distance"
	featuresWalksList "chameth.com/chameth.com/features/walks/list"
	featuresWalksSpeed "chameth.com/chameth.com/features/walks/speed"
	featuresWow "chameth.com/chameth.com/features/wow"
	featuresWowAchievements "chameth.com/chameth.com/features/wow/achievements"
	featuresWowAdmin "chameth.com/chameth.com/features/wow/admin"
	featuresWowChar "chameth.com/chameth.com/features/wow/char"
)

func (s *site) registerAssets() {
	assets.RegisterAssets(s.Assets)
	features.RegisterAssets(s.Assets)
	featuresAdmin.RegisterAssets(s.Assets)
	featuresFeeds.RegisterAssets(s.Assets)
	featuresShortcodesRating.RegisterAssets(s.Assets)
}

func (s *site) registerShortcodes() {
	featuresBoardgamesList.RegisterShortcodes(s.Shortcodes)
	featuresBoardgamesPlayed.RegisterShortcodes(s.Shortcodes)
	featuresContactForm.RegisterShortcodes(s.Shortcodes)
	featuresFilmsList.RegisterShortcodes(s.Shortcodes)
	featuresFilmsRatingdistribution.RegisterShortcodes(s.Shortcodes)
	featuresFilmsRecent.RegisterShortcodes(s.Shortcodes)
	featuresFilmsReview.RegisterShortcodes(s.Shortcodes)
	featuresFilmsReviews.RegisterShortcodes(s.Shortcodes)
	featuresFilmsSearch.RegisterShortcodes(s.Shortcodes)
	featuresFilmsWatched.RegisterShortcodes(s.Shortcodes)
	featuresMediaAudio.RegisterShortcodes(s.Shortcodes)
	featuresMediaFigure.RegisterShortcodes(s.Shortcodes)
	featuresMediaLabelledfigure.RegisterShortcodes(s.Shortcodes)
	featuresMediaVideo.RegisterShortcodes(s.Shortcodes)
	featuresMusicNowplaying.RegisterShortcodes(s.Shortcodes)
	featuresMusicTopalbums.RegisterShortcodes(s.Shortcodes)
	featuresMusicTopartists.RegisterShortcodes(s.Shortcodes)
	featuresNodForm.RegisterShortcodes(s.Shortcodes)
	featuresPostsLink.RegisterShortcodes(s.Shortcodes)
	featuresPostsRecent.RegisterShortcodes(s.Shortcodes)
	featuresShortcodesLink.RegisterShortcodes(s.Shortcodes)
	featuresShortcodesRating.RegisterShortcodes(s.Shortcodes)
	featuresShortcodesSidenote.RegisterShortcodes(s.Shortcodes)
	featuresShortcodesUpdate.RegisterShortcodes(s.Shortcodes)
	featuresShortcodesWarning.RegisterShortcodes(s.Shortcodes)
	featuresSyndicationsDisplay.RegisterShortcodes(s.Shortcodes)
	featuresWalksDistance.RegisterShortcodes(s.Shortcodes)
	featuresWalksList.RegisterShortcodes(s.Shortcodes)
	featuresWalksSpeed.RegisterShortcodes(s.Shortcodes)
	featuresWowAchievements.RegisterShortcodes(s.Shortcodes)
	featuresWowChar.RegisterShortcodes(s.Shortcodes)
}

func (s *site) registerRoutes() {
	assets.RegisterRoutes(s.Routes, s.Assets)
	featuresAdmin.RegisterRoutes(s.Routes, s.Assets)
	featuresBoardgamesAdmin.RegisterRoutes(s.Routes)
	featuresContact.RegisterRoutes(s.Routes)
	featuresFeeds.RegisterRoutes(s.Routes)
	featuresFilms.RegisterRoutes(s.Routes)
	featuresFilmsAdmin.RegisterRoutes(s.Routes)
	featuresGoimportsAdmin.RegisterRoutes(s.Routes)
	featuresMediaAdmin.RegisterRoutes(s.Routes)
	featuresNod.RegisterRoutes(s.Routes)
	featuresPagesAdmin.RegisterRoutes(s.Routes)
	featuresPastesAdmin.RegisterRoutes(s.Routes)
	featuresPoemsAdmin.RegisterRoutes(s.Routes)
	featuresPosts.RegisterRoutes(s.Routes)
	featuresPostsAdmin.RegisterRoutes(s.Routes)
	featuresPrints.RegisterRoutes(s.Routes)
	featuresProjects.RegisterRoutes(s.Routes)
	featuresProjectsAdmin.RegisterRoutes(s.Routes)
	featuresRouting.RegisterRoutes(s.Routes)
	featuresSitemap.RegisterRoutes(s.Routes)
	featuresSnippets.RegisterRoutes(s.Routes)
	featuresSnippetsAdmin.RegisterRoutes(s.Routes)
	featuresSudo.RegisterRoutes(s.Routes)
	featuresSyndicationsAdmin.RegisterRoutes(s.Routes)
	featuresVideogamesAdmin.RegisterRoutes(s.Routes)
	featuresWalksAdmin.RegisterRoutes(s.Routes)
	featuresWowAdmin.RegisterRoutes(s.Routes)
}

func (s *site) launchGoroutines() {
	go featuresAdmin.RegisterGoroutine(s.Tailscale, s.Routes)()
	go featuresMetrics.RegisterGoroutine()()
	go featuresMusic.RegisterGoroutine(s.Context, s.Tailscale)()
	go featuresPosts.RegisterGoroutine(s.Context)()
	go featuresSyndications.RegisterGoroutine(s.Context)()
	go featuresWow.RegisterGoroutine(s.Context)()
}

func (s *site) registerContentTypes() {
	featuresFilms.RegisterContentTypes(s.Routes)
	featuresGoimports.RegisterContentTypes(s.Routes)
	featuresMedia.RegisterContentTypes(s.Routes)
	featuresPages.RegisterContentTypes(s.Routes)
	featuresPastes.RegisterContentTypes(s.Routes)
	featuresPoems.RegisterContentTypes(s.Routes)
	featuresPosts.RegisterContentTypes(s.Routes)
	featuresSnippets.RegisterContentTypes(s.Routes)
}
