name: vuln check 

on:
  schedule:
    - cron: '30 */6 * * *'
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: meta/workflows/.forgejo/workflows/go-vulncheck.yml@master
    runs-on: docker
