baseUrl: https://chameth.com
assetDir: assets
disablePathToLower: true
languageCode: en-gb
title: Chameth.com
disableKinds: ["taxonomy", "taxonomyTerm"]

permalinks:
  post: /:slug

markup:
  goldmark:
    renderer:
      unsafe: true

pygmentsUseClasses: true
