package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type pkg struct {
	importPath    string
	alias         string
	hasShortcodes bool
	hasAssets     bool
}

func main() {
	root := repoRoot()
	mod := moduleName(filepath.Join(root, "go.mod"))
	pkgs := scan(root, mod)
	gen(root, mod, pkgs)
}

func die(msg string, args ...any) {
	fmt.Fprintf(os.Stderr, msg+"\n", args...)
	os.Exit(1)
}

func repoRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		die("failed to get working directory: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			die("could not find go.mod")
		}
		dir = parent
	}
}

func moduleName(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		die("failed to read go.mod: %v", err)
	}
	for line := range strings.SplitSeq(string(data), "\n") {
		line = strings.TrimSpace(line)
		if after, ok := strings.CutPrefix(line, "module "); ok {
			return strings.TrimSpace(after)
		}
	}
	die("module directive not found in go.mod")
	return ""
}

func makeAlias(mod, importPath string) string {
	rel := strings.TrimPrefix(importPath, mod+"/")
	parts := strings.Split(rel, "/")
	var a strings.Builder
	a.WriteString(parts[0])
	for _, p := range parts[1:] {
		a.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return a.String()
}

func scan(root, mod string) map[string]*pkg {
	pkgs := map[string]*pkg{}
	filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		if info.IsDir() {
			switch info.Name() {
			case ".git", ".postgres", "tsdata":
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			return nil
		}

		rel, err := filepath.Rel(root, path)
		if err != nil {
			return nil
		}
		dir := filepath.Dir(rel)
		if dir == "." {
			return nil
		}
		importPath := mod + "/" + filepath.ToSlash(dir)

		var sc, as bool
		for _, d := range f.Decls {
			fn, ok := d.(*ast.FuncDecl)
			if !ok {
				continue
			}
			switch fn.Name.Name {
			case "RegisterShortcodes":
				sc = true
			case "RegisterAssets":
				as = true
			}
		}
		if !sc && !as {
			return nil
		}

		p, ok := pkgs[importPath]
		if !ok {
			p = &pkg{importPath: importPath, alias: makeAlias(mod, importPath)}
			pkgs[importPath] = p
		}
		p.hasShortcodes = p.hasShortcodes || sc
		p.hasAssets = p.hasAssets || as
		return nil
	})
	return pkgs
}

func gen(root, mod string, pkgs map[string]*pkg) {
	shortcodesPath := mod + "/features/shortcodes"
	shortcodesAlias := makeAlias(mod, shortcodesPath)

	allImports := map[string]string{}
	for _, p := range pkgs {
		allImports[p.alias] = p.importPath
	}
	allImports[shortcodesAlias] = shortcodesPath

	sortedAliases := make([]string, 0, len(allImports))
	for a := range allImports {
		sortedAliases = append(sortedAliases, a)
	}
	sort.Strings(sortedAliases)

	sortedPaths := make([]string, 0, len(pkgs))
	for p := range pkgs {
		sortedPaths = append(sortedPaths, p)
	}
	sort.Strings(sortedPaths)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/generate. DO NOT EDIT.\n")
	buf.WriteString("//go:generate go run ../../cmd/generate\n\n")
	buf.WriteString("package main\n\n")
	buf.WriteString("import (\n")
	for _, a := range sortedAliases {
		fmt.Fprintf(&buf, "\t%s %q\n", a, allImports[a])
	}
	buf.WriteString(")\n\n")

	var assetPkgs, shortcodePkgs []*pkg
	for _, path := range sortedPaths {
		p := pkgs[path]
		if p.hasAssets {
			assetPkgs = append(assetPkgs, p)
		}
		if p.hasShortcodes {
			shortcodePkgs = append(shortcodePkgs, p)
		}
	}

	buf.WriteString("func registerAssets(mgr *assets.Manager) {\n")
	for _, p := range assetPkgs {
		fmt.Fprintf(&buf, "\t%s.RegisterAssets(mgr)\n", p.alias)
	}
	buf.WriteString("}\n\n")

	fmt.Fprintf(&buf, "func registerShortcodes(mgr *%s.Manager) {\n", shortcodesAlias)
	for _, p := range shortcodePkgs {
		fmt.Fprintf(&buf, "\t%s.RegisterShortcodes(mgr)\n", p.alias)
	}
	buf.WriteString("}\n")

	out := filepath.Join(root, "cmd", "serve", "register.go")
	if err := os.WriteFile(out, buf.Bytes(), 0644); err != nil {
		die("failed to write %s: %v", out, err)
	}
}
